/* ============================================================
   WA-NG'ASH STORES — Product Data & Testimonials
   ============================================================ */

const U = (id, w, h) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w||600}&h=${h||600}&q=80`;

const PRODUCTS = [
  /* ── Men's Shoes ── */
  {
    id: 1,
    name: "Oxford Classic Elite",
    category: "mens-shoes",
    gender: "men",
    price: 4500,
    originalPrice: 5800,
    rating: 4.8,
    reviews: 124,
    image: U('1460353581641-37baddab0fa2'),
    sizes: [39, 40, 41, 42, 43, 44, 45],
    tags: ["bestseller", "new"],
    description: "Crafted from premium full-grain leather, the Oxford Classic Elite offers timeless elegance with modern comfort. The cushioned insole and Goodyear welt construction ensure durability for years of distinguished wear.",
    features: ["Full-grain leather upper", "Goodyear welt construction", "Memory foam insole", "Slip-resistant rubber sole", "Breathable lining"],
    inStock: true
  },
  {
    id: 2,
    name: "Derby Suede Premium",
    category: "mens-shoes",
    gender: "men",
    price: 3800,
    originalPrice: null,
    rating: 4.6,
    reviews: 87,
    image: U('1545454675-8a7a20a5c065'),
    sizes: [39, 40, 41, 42, 43, 44, 45],
    tags: ["bestseller"],
    description: "The Derby Suede Premium blends casual sophistication with everyday comfort. Soft suede upper with a crepe rubber sole makes this the perfect shoe for smart-casual occasions.",
    features: ["Premium suede upper", "Crepe rubber sole", "Foam padded collar", "Anti-odor lining", "Handcrafted stitching"],
    inStock: true
  },
  {
    id: 3,
    name: "Chelsea Boot Pro",
    category: "mens-shoes",
    gender: "men",
    price: 5200,
    originalPrice: 6500,
    rating: 4.9,
    reviews: 203,
    image: U('1542291026-7eec264c27ff'),
    sizes: [40, 41, 42, 43, 44, 45],
    tags: ["bestseller", "popular"],
    description: "The Chelsea Boot Pro redefines urban style. With elastic side panels and a stacked leather heel, this boot moves seamlessly from boardroom to evening events.",
    features: ["Genuine calfskin leather", "Elastic side panels", "Stacked leather heel", "Leather-lined interior", "Durable outsole"],
    inStock: true
  },
  {
    id: 4,
    name: "Loafer Comfort Plus",
    category: "mens-shoes",
    gender: "men",
    price: 3200,
    originalPrice: null,
    rating: 4.5,
    reviews: 64,
    image: U('1614252235316-8c857d38b5f4'),
    sizes: [39, 40, 41, 42, 43, 44],
    tags: ["new"],
    description: "Slip into effortless style with the Loafer Comfort Plus. Featuring a soft leather upper and cushioned footbed, these loafers are perfect for long days at work or weekend outings.",
    features: ["Soft moccasin leather", "Cushioned footbed", "Flexible rubber sole", "Bit hardware accent", "Breathable mesh lining"],
    inStock: true
  },
  {
    id: 5,
    name: "Brogue Wingtip Classic",
    category: "mens-shoes",
    gender: "men",
    price: 4800,
    originalPrice: 5600,
    rating: 4.7,
    reviews: 91,
    image: U('1491553895911-0055eca6402d'),
    sizes: [39, 40, 41, 42, 43, 44, 45],
    tags: [],
    description: "The Brogue Wingtip Classic features the signature perforated detailing that has defined gentlemen's fashion for centuries. Crafted with precision, it's a statement of refined taste.",
    features: ["Perforated leather upper", "Wingtip design", "Leather welt sole", "Heel counter support", "Classic last shape"],
    inStock: true
  },
  {
    id: 6,
    name: "Sneaker Urban Runner",
    category: "mens-shoes",
    gender: "men",
    price: 2800,
    originalPrice: 3500,
    rating: 4.4,
    reviews: 156,
    image: U('1607522370275-f14206abe5d3'),
    sizes: [40, 41, 42, 43, 44, 45],
    tags: ["sale"],
    description: "Meet the Urban Runner — where streetwear meets performance. Lightweight mesh upper keeps your feet cool, while the responsive cushioning handles city miles in style.",
    features: ["Breathable mesh upper", "EVA cushioning midsole", "Rubber outsole traction", "Padded ankle collar", "Reflective details"],
    inStock: true
  },
  /* ── Women's Shoes ── */
  {
    id: 7,
    name: "Stiletto Grace",
    category: "womens-shoes",
    gender: "women",
    price: 3900,
    originalPrice: 4800,
    rating: 4.7,
    reviews: 189,
    image: U('1543163521-1bf539c55dd2'),
    sizes: [36, 37, 38, 39, 40, 41],
    tags: ["bestseller", "popular"],
    description: "The Stiletto Grace embodies feminine power. With a 10cm heel and pointed toe, this shoe elongates the silhouette while the padded insole ensures you stay comfortable all night long.",
    features: ["Patent leather upper", "10cm stiletto heel", "Pointed toe design", "Cushioned insole", "Suede lining"],
    inStock: true
  },
  {
    id: 8,
    name: "Wedge Elegance",
    category: "womens-shoes",
    gender: "women",
    price: 3400,
    originalPrice: null,
    rating: 4.6,
    reviews: 112,
    image: U('1515347619252-60a4bf4fff4f'),
    sizes: [36, 37, 38, 39, 40, 41],
    tags: ["new"],
    description: "Combine height and comfort with the Wedge Elegance. The espadrille-inspired wedge sole provides stability while the ankle strap adds a touch of bohemian chic.",
    features: ["Leather upper", "6cm wedge heel", "Ankle strap closure", "Jute-wrapped wedge", "Non-slip sole"],
    inStock: true
  },
  {
    id: 9,
    name: "Ballet Flat Luxe",
    category: "womens-shoes",
    gender: "women",
    price: 2600,
    originalPrice: 3200,
    rating: 4.8,
    reviews: 247,
    image: U('1598532163257-ae3c6b2524b6'),
    sizes: [35, 36, 37, 38, 39, 40, 41],
    tags: ["bestseller"],
    description: "The Ballet Flat Luxe proves that flats can be just as glamorous. Ultra-soft nappa leather molds to your foot for a bespoke fit, with a delicate bow accent for feminine flair.",
    features: ["Nappa leather upper", "Flexible rubber sole", "Decorative bow accent", "Cushioned footbed", "Slip-on design"],
    inStock: true
  },
  {
    id: 10,
    name: "Ankle Boot Chic",
    category: "womens-shoes",
    gender: "women",
    price: 4600,
    originalPrice: 5500,
    rating: 4.9,
    reviews: 178,
    image: U('1619116083702-be8cfce7a8c8'),
    sizes: [36, 37, 38, 39, 40, 41],
    tags: ["bestseller", "new"],
    description: "The Ankle Boot Chic is your go-to for effortless autumn style. A block heel provides height without sacrificing comfort, and the zip closure ensures an easy, secure fit.",
    features: ["Nubuck leather upper", "5cm block heel", "Side zip closure", "Almond toe shape", "Leather-lined shaft"],
    inStock: true
  },
  {
    id: 11,
    name: "Platform Sandal Luxe",
    category: "womens-shoes",
    gender: "women",
    price: 3100,
    originalPrice: null,
    rating: 4.5,
    reviews: 93,
    image: U('1583292650898-7d22cd27ca6f'),
    sizes: [36, 37, 38, 39, 40],
    tags: ["new"],
    description: "Make every step count with the Platform Sandal Luxe. The 4cm platform sole adds drama to your look while the adjustable ankle strap ensures a perfect fit every time.",
    features: ["Leather straps", "4cm platform sole", "Adjustable ankle strap", "Non-slip outsole", "Lightly cushioned footbed"],
    inStock: true
  },
  {
    id: 12,
    name: "Mule Sophistiqué",
    category: "womens-shoes",
    gender: "women",
    price: 2900,
    originalPrice: 3600,
    rating: 4.4,
    reviews: 67,
    image: U('1603487742131-4160ec999306'),
    sizes: [36, 37, 38, 39, 40, 41],
    tags: ["sale"],
    description: "The Mule Sophistiqué combines the ease of slip-on wear with a polished kitten heel. Perfect for transitioning from desk to dinner effortlessly.",
    features: ["Suede upper", "4cm kitten heel", "Slip-on design", "Padded footbed", "Rubber sole"],
    inStock: true
  },
  /* ── Men's Eyeglasses ── */
  {
    id: 13,
    name: "Executive Frame Pro",
    category: "mens-eyeglasses",
    gender: "men",
    price: 2800,
    originalPrice: 3500,
    rating: 4.7,
    reviews: 83,
    image: U('1574258495973-f010dfbb5371'),
    sizes: ["Small", "Medium", "Large"],
    tags: ["bestseller"],
    description: "The Executive Frame Pro projects authority and intelligence. Crafted from lightweight titanium with acetate temples, these frames offer all-day comfort without compromising style.",
    features: ["Titanium frame", "Acetate temples", "Hypoallergenic nose pads", "UV400 lens protection", "Scratch-resistant coating"],
    inStock: true
  },
  {
    id: 14,
    name: "Aviator Classic Gold",
    category: "mens-eyeglasses",
    gender: "men",
    price: 2200,
    originalPrice: null,
    rating: 4.8,
    reviews: 134,
    image: U('1509695507497-903c140c43b0'),
    sizes: ["One Size"],
    tags: ["bestseller", "popular"],
    description: "The Aviator Classic Gold never goes out of style. The gold metal frame and teardrop lens shape have been a fashion staple since the 1930s — and with good reason.",
    features: ["Gold-tone metal frame", "Teardrop lens", "Spring hinge temples", "Adjustable nose pads", "100% UV protection"],
    inStock: true
  },
  {
    id: 15,
    name: "Wayfarer Bold",
    category: "mens-eyeglasses",
    gender: "men",
    price: 1900,
    originalPrice: 2500,
    rating: 4.5,
    reviews: 72,
    image: U('1591076482161-42ce6da69f67'),
    sizes: ["Small", "Medium", "Large"],
    tags: ["sale"],
    description: "The Wayfarer Bold is the iconic silhouette for the modern man. Thick acetate frames in a classic trapezoidal shape give you instant cool-factor.",
    features: ["Premium acetate frame", "Keyhole bridge", "Spring hinge", "Wide temple tips", "Polarized lenses available"],
    inStock: true
  },
  {
    id: 16,
    name: "Round Scholar",
    category: "mens-eyeglasses",
    gender: "men",
    price: 2100,
    originalPrice: null,
    rating: 4.6,
    reviews: 58,
    image: U('1512361436605-a484bdb34b5f'),
    sizes: ["Small", "Medium"],
    tags: ["new"],
    description: "Channel intellectual style with the Round Scholar. Fine metal wire frames give a refined, minimalist look that works equally well for formal presentations or creative settings.",
    features: ["Fine metal wire frame", "Round lens shape", "Thin bridge", "Slim temples", "Anti-reflective coating"],
    inStock: true
  },
  /* ── Women's Eyeglasses ── */
  {
    id: 17,
    name: "Cat-Eye Glamour",
    category: "womens-eyeglasses",
    gender: "women",
    price: 2400,
    originalPrice: 3000,
    rating: 4.9,
    reviews: 167,
    image: U('1556306535-0f09a537f0a3'),
    sizes: ["Small", "Medium", "Large"],
    tags: ["bestseller", "popular"],
    description: "Turn heads with the Cat-Eye Glamour. The dramatic upswept corners exude vintage Hollywood glamour, while modern acetate materials ensure lightweight comfort.",
    features: ["Premium acetate frame", "Cat-eye silhouette", "Tortoiseshell options", "Spring hinges", "Anti-UV coating"],
    inStock: true
  },
  {
    id: 18,
    name: "Butterfly Chic",
    category: "womens-eyeglasses",
    gender: "women",
    price: 2700,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    image: U('1583394838336-acd977736f90'),
    sizes: ["Small", "Medium"],
    tags: ["new"],
    description: "The Butterfly Chic frames are delicate yet bold. The oversized butterfly silhouette offers maximum UV coverage while the acetate frame comes in a range of beautiful colors.",
    features: ["Oversized butterfly frame", "Premium acetate", "Polarized lens option", "Adjustable nose bridge", "Spring flex hinges"],
    inStock: true
  },
  {
    id: 19,
    name: "Oval Minimalist",
    category: "womens-eyeglasses",
    gender: "women",
    price: 1800,
    originalPrice: 2400,
    rating: 4.5,
    reviews: 51,
    image: U('1574258495973-f010dfbb5371&crop=bottom'),
    sizes: ["Small", "Medium"],
    tags: ["sale"],
    description: "The Oval Minimalist embodies understated elegance. Clean lines and a subtle color palette make these frames the perfect everyday companion.",
    features: ["Metal oval frame", "Slim bridge design", "Lightweight titanium", "Clear or tinted lenses", "Anti-scratch coating"],
    inStock: true
  },
  {
    id: 20,
    name: "Oversized Fashion Lens",
    category: "womens-eyeglasses",
    gender: "women",
    price: 2900,
    originalPrice: 3500,
    rating: 4.6,
    reviews: 114,
    image: U('1509695507497-903c140c43b0&crop=top'),
    sizes: ["Medium", "Large"],
    tags: ["popular"],
    description: "Make a statement with the Oversized Fashion Lens. These bold, wide frames are a favorite among fashion-forward women who know that eyewear is the ultimate accessory.",
    features: ["Wide acetate frame", "Oversized lens", "Logo temple detail", "UV400 protection", "Gradient lens options"],
    inStock: true
  },
  /* ── Purses & Handbags ── */
  {
    id: 21,
    name: "Executive Tote Luxe",
    category: "purses",
    gender: "women",
    price: 6800,
    originalPrice: 8500,
    rating: 4.9,
    reviews: 212,
    image: U('1548036328-c9fa89d128fa'),
    sizes: ["One Size"],
    tags: ["bestseller", "popular"],
    description: "The Executive Tote Luxe is the ultimate power bag. Spacious enough for your laptop, files, and all daily essentials, with an organizational interior that keeps everything in its place.",
    features: ["Full-grain leather", "Interior laptop sleeve", "Magnetic closure", "Gold-tone hardware", "Detachable shoulder strap"],
    inStock: true
  },
  {
    id: 22,
    name: "Crossbody Mini Classic",
    category: "purses",
    gender: "women",
    price: 3600,
    originalPrice: null,
    rating: 4.7,
    reviews: 156,
    image: U('1584917865442-de89df76afd3'),
    sizes: ["One Size"],
    tags: ["bestseller"],
    description: "Compact yet capable, the Crossbody Mini Classic holds all your essentials with room to spare. The adjustable strap means you can wear it your way.",
    features: ["Pebbled leather", "Adjustable chain strap", "Zip-top closure", "Card slots inside", "Suede lining"],
    inStock: true
  },
  {
    id: 23,
    name: "Clutch Evening Gold",
    category: "purses",
    gender: "women",
    price: 2800,
    originalPrice: 3500,
    rating: 4.8,
    reviews: 98,
    image: U('1553062407-98eeb64c6a62'),
    sizes: ["One Size"],
    tags: ["popular", "new"],
    description: "The Clutch Evening Gold is your ticket to any event. The metallic gold finish catches the light beautifully, making this the perfect accessory for weddings, galas, and formal dinners.",
    features: ["Metallic leather", "Push-lock closure", "Chain wrist strap", "Satin-lined interior", "Compact zip pocket"],
    inStock: true
  },
  {
    id: 24,
    name: "Shoulder Bag Classic",
    category: "purses",
    gender: "women",
    price: 5200,
    originalPrice: 6400,
    rating: 4.6,
    reviews: 135,
    image: U('1566150905458-1bf1fc113f0d'),
    sizes: ["Small", "Large"],
    tags: ["bestseller"],
    description: "The Shoulder Bag Classic is a wardrobe staple. Clean lines, quality hardware, and a structured silhouette that looks just as at home at a business lunch as it does at dinner.",
    features: ["Saffiano leather", "Double handle", "Zip closure", "Interior pockets", "Dust bag included"],
    inStock: true
  },
  {
    id: 25,
    name: "Backpack Urban Chic",
    category: "purses",
    gender: "women",
    price: 4400,
    originalPrice: null,
    rating: 4.5,
    reviews: 77,
    image: U('1622560480605-d83c853bc5c3'),
    sizes: ["One Size"],
    tags: ["new"],
    description: "The Backpack Urban Chic marries form and function. Designed for the modern woman on the go, it combines stylish leather detailing with practical compartments.",
    features: ["Premium leather exterior", "Laptop compartment", "Anti-theft back pocket", "Adjustable straps", "Water-resistant lining"],
    inStock: true
  },
  {
    id: 26,
    name: "Wristlet Card Holder",
    category: "purses",
    gender: "women",
    price: 1800,
    originalPrice: 2400,
    rating: 4.4,
    reviews: 89,
    image: U('1523779105320-d1cd346ff52b'),
    sizes: ["One Size"],
    tags: ["sale"],
    description: "The Wristlet Card Holder is perfect for nights when you want to travel light. Multiple card slots, a cash compartment, and a detachable wrist strap make it the ultimate minimalist wallet-bag.",
    features: ["Slim leather construction", "8 card slots", "Cash compartment", "Wrist strap included", "RFID blocking lining"],
    inStock: true
  }
];

const TESTIMONIALS = [
  {
    id: 1,
    name: "Amina Wanjiru",
    location: "Nairobi, Kenya",
    initials: "AW",
    color: "#C9975E",
    rating: 5,
    text: "I've been shopping at Wa-ng'ash for two years now and the quality never disappoints. My Oxford Classics are still going strong after 18 months of daily wear. Worth every shilling!",
    product: "Oxford Classic Elite"
  },
  {
    id: 2,
    name: "Brian Ochieng",
    location: "Mombasa, Kenya",
    initials: "BO",
    color: "#1C1916",
    rating: 5,
    text: "The Chelsea Boots I bought last month are absolutely stunning. Got so many compliments at work. The packaging was also beautiful — it felt like unwrapping a gift.",
    product: "Chelsea Boot Pro"
  },
  {
    id: 3,
    name: "Fatuma Haji",
    location: "Kisumu, Kenya",
    initials: "FH",
    color: "#5C564F",
    rating: 5,
    text: "Found my dream cat-eye glasses here! The frames are lightweight and the customer service was exceptional — they helped me find the perfect fit. Highly recommend!",
    product: "Cat-Eye Glamour"
  },
  {
    id: 4,
    name: "James Kamau",
    location: "Nakuru, Kenya",
    initials: "JK",
    color: "#A87A42",
    rating: 4,
    text: "Ordered the Executive Tote for my wife's birthday and she absolutely loves it. The leather quality is top-notch and it looks even better in person. Will definitely shop here again.",
    product: "Executive Tote Luxe"
  },
  {
    id: 5,
    name: "Grace Nyambura",
    location: "Eldoret, Kenya",
    initials: "GN",
    color: "#6E6560",
    rating: 5,
    text: "The Ballet Flat Luxe are so comfortable I forgot I was even wearing shoes! I wore them for 8 hours at a function and had zero pain. The bow detail is delicate and beautiful.",
    product: "Ballet Flat Luxe"
  },
  {
    id: 6,
    name: "Samuel Mutua",
    location: "Thika, Kenya",
    initials: "SM",
    color: "#2E2A26",
    rating: 5,
    text: "Best shoe store in Kenya hands down. The Aviator glasses I got are perfect — sturdy, stylish and the UV protection is great for our Nairobi sun. Quick delivery too!",
    product: "Aviator Classic Gold"
  }
];

const CATEGORIES = [
  { id: "mens-shoes",       label: "Men's Shoes",       image: U('1542291026-7eec264c27ff', 600, 800), count: 6,  genders: ["men"] },
  { id: "womens-shoes",     label: "Women's Shoes",     image: U('1543163521-1bf539c55dd2', 600, 800), count: 6,  genders: ["women"] },
  { id: "eyeglasses",       label: "Eyeglasses",        image: U('1574258495973-f010dfbb5371', 600, 800), count: 8,  genders: ["men", "women"] },
  { id: "purses",           label: "Purses & Handbags", image: U('1548036328-c9fa89d128fa', 600, 800), count: 6,  genders: ["women"] }
];
